package gui.standalone;

import clil.xml.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;
import javax.swing.event.*;

public class FindNote extends javax.swing.JPanel 
                      implements ListSelectionListener{
    Date currentDate;
    private Notebook nb;
    private ArrayList<Note> notesOfDate;
    
    public FindNote(Notebook nb) {
        initComponents();
        lbError.setVisible(false);
        this.nb = nb;
        noteList.addListSelectionListener(this);
    }
    
    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (e.getValueIsAdjusting()== false) {
            int selectedNote = noteList.getSelectedIndex();
            if (selectedNote == -1) {
                btnEliminaNota.setEnabled(false);
            } else {
                btnEliminaNota.setEnabled(true);
                selectedNoteText.setText(notesOfDate.get(selectedNote).getDescription());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        selectedNoteText = new javax.swing.JTextArea();
        btnEliminaNota = new javax.swing.JButton();
        btnTrova = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel1.setText("Note del giorno");

        lbData.setText("Data:");

        txtData.setToolTipText("gg/mm/aaaa");

        noteList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(noteList);

        selectedNoteText.setEditable(false);
        selectedNoteText.setColumns(20);
        selectedNoteText.setRows(5);
        jScrollPane3.setViewportView(selectedNoteText);

        btnEliminaNota.setText("Elimina nota ");
        btnEliminaNota.setEnabled(false);
        btnEliminaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaNotaActionPerformed(evt);
            }
        });

        btnTrova.setText("Trova");
        btnTrova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrovaActionPerformed(evt);
            }
        });

        lbError.setForeground(new java.awt.Color(255, 0, 0));
        lbError.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrova))
                    .addComponent(btnEliminaNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbError))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrova)
                    .addComponent(lbError))
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminaNota)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrovaActionPerformed
        SimpleDateFormat dateformat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            currentDate = dateformat.parse(txtData.getText());
            setNoteList();
        } catch (ParseException ex) {
            lbError.setText("Data non valida!");
            lbError.setVisible(true);
        }
    }//GEN-LAST:event_btnTrovaActionPerformed

    private void btnEliminaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaNotaActionPerformed
        int selectedNote = noteList.getSelectedIndex();
        nb.getNotes().removeIf(n -> n.equals(notesOfDate.get(selectedNote)));
        noteList.removeAll();
        setNoteList();
    }//GEN-LAST:event_btnEliminaNotaActionPerformed

    private void setNoteList() {
        SimpleDateFormat timeformat = new SimpleDateFormat("HH:mm:ss");
        notesOfDate = nb.GetNotesByDate(currentDate);
        lbError.setVisible(false);
        String[] noteItems = new String[notesOfDate.size()];
        int i=0;
        for (Note note : notesOfDate) {
            noteItems[i] = timeformat.format(note.getCreation());
            i++;
        }
        noteList.setListData(noteItems);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminaNota;
    private javax.swing.JButton btnTrova;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbError;
    private javax.swing.JList<String> noteList;
    private javax.swing.JTextArea selectedNoteText;
    private javax.swing.JTextField txtData;
    // End of variables declaration//GEN-END:variables
}
